version: "3.8"

services:
  core_django:
    build: .
    container_name: core_django
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8000:8000
    environment:
      - DJANGO_SUPERUSER_PASSWORD=Talks.2021
      - DJANGO_SUPERUSER_EMAIL=example@example.com
      - DJANGO_SUPERUSER_USERNAME=admin
    depends_on:
      - db
  core_nginx:
    build: ./config/nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 80:80
    depends_on:
      - core_django
  db:
    image: postgres
    container_name: db_001
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  static_volume:
  media_volume: